#include <cpio.h>

#include "util.h"

IDENT_INT(C_IRUSR);
IDENT_INT(C_IWUSR);
IDENT_INT(C_IXUSR);
IDENT_INT(C_IRGRP);
IDENT_INT(C_IWGRP);
IDENT_INT(C_IXGRP);
IDENT_INT(C_IROTH);
IDENT_INT(C_IWOTH);
IDENT_INT(C_IXOTH);
IDENT_INT(C_ISUID);
IDENT_INT(C_ISGID);
IDENT_INT(C_ISVTX);
IDENT_INT(C_ISDIR);
IDENT_INT(C_ISFIFO);
IDENT_INT(C_ISREG);
IDENT_INT(C_ISBLK);
IDENT_INT(C_ISCHR);
IDENT_INT(C_ISCTG);
IDENT_INT(C_ISLNK);
IDENT_INT(C_ISSOCK);

IDENT(MAGIC, char *);
