#include <float.h>

#include "util.h"

IDENT_INT(FLT_ROUNDS);
IDENT_INT(FLT_EVAL_METHOD);
IDENT_INT(FLT_RADIX);

IDENT_INT(FLT_MANT_DIG);
IDENT_INT(DBL_MANT_DIG);
IDENT_INT(LDBL_MANT_DIG);

IDENT_INT(DECIMAL_DIG);

IDENT_INT(FLT_DIG);
IDENT_INT(DBL_DIG);
IDENT_INT(LDBL_DIG);

IDENT_INT(FLT_MIN_EXP);
IDENT_INT(DBL_MIN_EXP);
IDENT_INT(LDBL_MIN_EXP);

IDENT_INT(FLT_MIN_10_EXP);
IDENT_INT(DBL_MIN_10_EXP);
IDENT_INT(LDBL_MIN_10_EXP);

IDENT_INT(FLT_MAX_EXP);
IDENT_INT(DBL_MAX_EXP);
IDENT_INT(LDBL_MAX_EXP);

IDENT_INT(FLT_MAX_10_EXP);
IDENT_INT(DBL_MAX_10_EXP);
IDENT_INT(DBL_MAX_10_EXP);

IDENT(FLT_MAX, float);
IDENT(DBL_MAX, double);
IDENT(LDBL_MAX, long double);

IDENT(FLT_EPSILON, float);
IDENT(DBL_EPSILON, double);
IDENT(LDBL_EPSILON, long double);

IDENT(FLT_MIN, float);
IDENT(DBL_MIN, double);
IDENT(LDBL_MIN, long double);
