#ifndef TRANSITIVE
#include <stdint.h>
#endif

#include "util.h"

TYPE_SINT(int8_t);
TYPE_SINT(int16_t);
TYPE_SINT(int32_t);
TYPE_UINT(uint8_t);
TYPE_UINT(uint16_t);
TYPE_UINT(uint32_t);

TYPE_SINT(int_least8_t);
TYPE_SINT(int_least16_t);
TYPE_SINT(int_least32_t);
TYPE_SINT(int_least64_t);
TYPE_UINT(uint_least8_t);
TYPE_UINT(uint_least16_t);
TYPE_UINT(uint_least32_t);
TYPE_UINT(uint_least64_t);

TYPE_SINT(int_fast8_t);
TYPE_SINT(int_fast16_t);
TYPE_SINT(int_fast32_t);
TYPE_SINT(int_fast64_t);
TYPE_UINT(uint_fast8_t);
TYPE_UINT(uint_fast16_t);
TYPE_UINT(uint_fast32_t);
TYPE_UINT(uint_fast64_t);

TYPE_SINT(intptr_t);
TYPE_UINT(uintptr_t);

TYPE_SINT(intmax_t);
TYPE_UINT(uintmax_t);

IDENT_INT(INT8_MIN);
IDENT_INT(INT16_MIN);
IDENT_INT(INT32_MIN);
IDENT_INT(INT64_MIN);
IDENT_INT(INT8_MAX);
IDENT_INT(INT16_MAX);
IDENT_INT(INT32_MAX);
IDENT_INT(INT64_MAX);
IDENT_INT(UINT8_MAX);
IDENT_INT(UINT16_MAX);
IDENT_INT(UINT32_MAX);
IDENT_INT(UINT64_MAX);

IDENT_INT(INT_LEAST8_MIN);
IDENT_INT(INT_LEAST16_MIN);
IDENT_INT(INT_LEAST32_MIN);
IDENT_INT(INT_LEAST64_MIN);
IDENT_INT(INT_LEAST8_MAX);
IDENT_INT(INT_LEAST16_MAX);
IDENT_INT(INT_LEAST32_MAX);
IDENT_INT(INT_LEAST64_MAX);
IDENT_INT(UINT_LEAST8_MAX);
IDENT_INT(UINT_LEAST16_MAX);
IDENT_INT(UINT_LEAST32_MAX);
IDENT_INT(UINT_LEAST64_MAX);

IDENT_INT(INT_FAST8_MIN);
IDENT_INT(INT_FAST16_MIN);
IDENT_INT(INT_FAST32_MIN);
IDENT_INT(INT_FAST64_MIN);
IDENT_INT(INT_FAST8_MAX);
IDENT_INT(INT_FAST16_MAX);
IDENT_INT(INT_FAST32_MAX);
IDENT_INT(INT_FAST64_MAX);
IDENT_INT(UINT_FAST8_MAX);
IDENT_INT(UINT_FAST16_MAX);
IDENT_INT(UINT_FAST32_MAX);
IDENT_INT(UINT_FAST64_MAX);

IDENT_INT(INTPTR_MIN);
IDENT_INT(INTPTR_MAX);
IDENT_INT(UINTPTR_MAX);

IDENT_INT(INTMAX_MIN);
IDENT_INT(INTMAX_MAX);
IDENT_INT(UINTMAX_MAX);

IDENT_INT(PTRDIFF_MIN);
IDENT_INT(PTRDIFF_MAX);

IDENT_INT(SIG_ATOMIC_MIN);
IDENT_INT(SIG_ATOMIC_MAX);

IDENT_INT(SIZE_MAX);

IDENT_INT(WCHAR_MIN);
IDENT_INT(WCHAR_MAX);

IDENT_INT(WINT_MIN);
IDENT_INT(WINT_MAX);

IDENT_INT(INT8_C(0));
IDENT_INT(INT16_C(0));
IDENT_INT(INT32_C(0));
IDENT_INT(INT64_C(0));
IDENT_INT(UINT8_C(0));
IDENT_INT(UINT16_C(0));
IDENT_INT(UINT32_C(0));
IDENT_INT(UINT64_C(0));

IDENT_INT(INTMAX_C(0));
IDENT_INT(UINTMAX_C(0));
