#include <syslog.h>

#include "util.h"

IDENT_INT(LOG_PID);
IDENT_INT(LOG_CONS);
IDENT_INT(LOG_NDELAY);
IDENT_INT(LOG_ODELAY);
IDENT_INT(LOG_NOWAIT);

IDENT_INT(LOG_KERN);
IDENT_INT(LOG_USER);
IDENT_INT(LOG_MAIL);
IDENT_INT(LOG_NEWS);
IDENT_INT(LOG_UUCP);
IDENT_INT(LOG_DAEMON);
IDENT_INT(LOG_AUTH);
IDENT_INT(LOG_CRON);
IDENT_INT(LOG_LPR);
IDENT_INT(LOG_LOCAL0);
IDENT_INT(LOG_LOCAL1);
IDENT_INT(LOG_LOCAL2);
IDENT_INT(LOG_LOCAL3);
IDENT_INT(LOG_LOCAL4);
IDENT_INT(LOG_LOCAL5);
IDENT_INT(LOG_LOCAL6);
IDENT_INT(LOG_LOCAL7);

IDENT(LOG_MASK(0), int);

IDENT_INT(LOG_EMERG);
IDENT_INT(LOG_ALERT);
IDENT_INT(LOG_CRIT);
IDENT_INT(LOG_ERR);
IDENT_INT(LOG_WARNING);
IDENT_INT(LOG_NOTICE);
IDENT_INT(LOG_INFO);
IDENT_INT(LOG_DEBUG);

IDENT(closelog, void (*)(void));
IDENT(openlog, void (*)(const char *, int, int));
IDENT(setlogmask, int (*)(int));
IDENT(syslog, void (*)(int, const char *, ...));
