#include <limits.h>

#include "test_util.h"

#ifdef AIO_LISTIO_MAX
IDENT_INT(AIO_LISTIO_MAX);
#endif
#ifdef AIO_MAX
IDENT_INT(AIO_MAX);
#endif
#ifdef AIO_PRIO_DELTA_MAX
IDENT_INT(AIO_PRIO_DELTA_MAX);
#endif
#ifdef ARG_MAX
IDENT_INT(ARG_MAX);
#endif
#ifdef ATEXIT_MAX
IDENT_INT(ATEXIT_MAX);
#endif
#ifdef CHILD_MAX
IDENT_INT(CHILD_MAX);
#endif
#ifdef DELAYTIMER_MAX
IDENT_INT(DELAYTIMER_MAX);
#endif
#ifdef HOST_NAME_MAX
IDENT_INT(HOST_NAME_MAX);
#endif
#ifdef IOV_MAX
IDENT_INT(IOV_MAX);
#endif
#ifdef LOGIN_NAME_MAX
IDENT_INT(LOGIN_NAME_MAX);
#endif
#ifdef MQ_OPEN_MAX
IDENT_INT(MQ_OPEN_MAX);
#endif
#ifdef MQ_PRIO_MAX
IDENT_INT(MQ_PRIO_MAX);
#endif
#ifdef OPEN_MAX
IDENT_INT(OPEN_MAX);
#endif
#ifdef PAGESIZE
IDENT_INT(PAGESIZE);
#endif
#ifdef PAGE_SIZE
IDENT_INT(PAGE_SIZE);
#endif
#ifdef PTHREAD_DESTRUCTOR_ITERATIONS
IDENT_INT(PTHREAD_DESTRUCTOR_ITERATIONS);
#endif
#ifdef PTHREAD_KEYS_MAX
IDENT_INT(PTHREAD_KEYS_MAX);
#endif
#ifdef PTHREAD_STACK_MIN
IDENT_INT(PTHREAD_STACK_MIN);
#endif
#ifdef PTHREAD_THREADS_MAX
IDENT_INT(PTHREAD_THREADS_MAX);
#endif
#ifdef RE_DUP_MAX
IDENT_INT(RE_DUP_MAX);
#endif
#ifdef RTSIG_MAX
IDENT_INT(RTSIG_MAX);
#endif
#ifdef SEM_NSEMS_MAX
IDENT_INT(SEM_NSEMS_MAX);
#endif
#ifdef SEM_VALUE_MAX
IDENT_INT(SEM_VALUE_MAX);
#endif
#ifdef SIGQUEUE_MAX
IDENT_INT(SIGQUEUE_MAX);
#endif
#ifdef SS_REPL_MAX
IDENT_INT(SS_REPL_MAX);
#endif
#ifdef STREAM_MAX
IDENT_INT(STREAM_MAX);
#endif
#ifdef SYMLOOP_MAX
IDENT_INT(SYMLOOP_MAX);
#endif
#ifdef TIMER_MAX
IDENT_INT(TIMER_MAX);
#endif
#ifdef TRACE_EVENT_NAME_MAX
IDENT_INT(TRACE_EVENT_NAME_MAX);
#endif
#ifdef TRACE_NAME_MAX
IDENT_INT(TRACE_NAME_MAX);
#endif
#ifdef TRACE_SYS_MAX
IDENT_INT(TRACE_SYS_MAX);
#endif
#ifdef TRACE_USER_EVENT_MAX
IDENT_INT(TRACE_USER_EVENT_MAX);
#endif
#ifdef TTY_NAME_MAX
IDENT_INT(TTY_NAME_MAX);
#endif
#ifdef TZNAME_MAX
IDENT_INT(TZNAME_MAX);
#endif

#ifdef FILESIZEBITS
IDENT_INT(FILESIZEBITS);
#endif
#ifdef LINK_MAX
IDENT_INT(LINK_MAX);
#endif
#ifdef MAX_CANON
IDENT_INT(MAX_CANON);
#endif
#ifdef MAX_INPUT
IDENT_INT(MAX_INPUT);
#endif
#ifdef NAME_MAX
IDENT_INT(NAME_MAX);
#endif
#ifdef PATH_MAX
IDENT_INT(PATH_MAX);
#endif
#ifdef PIPE_BUF
IDENT_INT(PIPE_BUF);
#endif
#ifdef POSIX_ALLOC_SIZE_MIN
IDENT_INT(POSIX_ALLOC_SIZE_MIN);
#endif
#ifdef POSIX_REC_INCR_XFER_SIZE
IDENT_INT(POSIX_REC_INCR_XFER_SIZE);
#endif
#ifdef POSIX_REC_MAX_XFER_SIZE
IDENT_INT(POSIX_REC_MAX_XFER_SIZE);
#endif
#ifdef POSIX_REC_MIN_XFER_SIZE
IDENT_INT(POSIX_REC_MIN_XFER_SIZE);
#endif
#ifdef POSIX_REC_XFER_ALIGN
IDENT_INT(POSIX_REC_XFER_ALIGN);
#endif
#ifdef SYMLINK_MAX
IDENT_INT(SYMLINK_MAX);
#endif

IDENT_INT(BC_BASE_MAX);
IDENT_INT(BC_DIM_MAX);
IDENT_INT(BC_SCALE_MAX);
IDENT_INT(BC_STRING_MAX);
IDENT_INT(CHARCLASS_NAME_MAX);
IDENT_INT(COLL_WEIGHTS_MAX);
IDENT_INT(EXPR_NEST_MAX);
IDENT_INT(LINE_MAX);
IDENT_INT(NGROUPS_MAX);
IDENT_INT(RE_DUP_MAX);

IDENT_INT(_POSIX_CLOCKRES_MIN);

IDENT_INT(_POSIX_AIO_LISTIO_MAX);
IDENT_INT(_POSIX_AIO_MAX);
IDENT_INT(_POSIX_ARG_MAX);
IDENT_INT(_POSIX_CHILD_MAX);
IDENT_INT(_POSIX_DELAYTIMER_MAX);
IDENT_INT(_POSIX_HOST_NAME_MAX);
IDENT_INT(_POSIX_LINK_MAX);
IDENT_INT(_POSIX_LOGIN_NAME_MAX);
IDENT_INT(_POSIX_MAX_CANON);
IDENT_INT(_POSIX_MAX_INPUT);
IDENT_INT(_POSIX_MQ_OPEN_MAX);
IDENT_INT(_POSIX_MQ_PRIO_MAX);
IDENT_INT(_POSIX_NAME_MAX);
IDENT_INT(_POSIX_NGROUPS_MAX);
IDENT_INT(_POSIX_OPEN_MAX);
IDENT_INT(_POSIX_PATH_MAX);
IDENT_INT(_POSIX_PIPE_BUF);
IDENT_INT(_POSIX_RE_DUP_MAX);
IDENT_INT(_POSIX_RTSIG_MAX);
IDENT_INT(_POSIX_SEM_NSEMS_MAX);
IDENT_INT(_POSIX_SEM_VALUE_MAX);
IDENT_INT(_POSIX_SIGQUEUE_MAX);
IDENT_INT(_POSIX_SSIZE_MAX);
IDENT_INT(_POSIX_SS_REPL_MAX);
IDENT_INT(_POSIX_STREAM_MAX);
IDENT_INT(_POSIX_SYMLINK_MAX);
IDENT_INT(_POSIX_SYMLOOP_MAX);
IDENT_INT(_POSIX_THREAD_DESTRUCTOR_ITERATIONS);
IDENT_INT(_POSIX_THREAD_KEYS_MAX);
IDENT_INT(_POSIX_THREAD_THREADS_MAX);
IDENT_INT(_POSIX_TIMER_MAX);
IDENT_INT(_POSIX_TRACE_EVENT_NAME_MAX);
IDENT_INT(_POSIX_TRACE_NAME_MAX);
IDENT_INT(_POSIX_TRACE_SYS_MAX);
IDENT_INT(_POSIX_TRACE_USER_EVENT_MAX);
IDENT_INT(_POSIX_TTY_NAME_MAX);
IDENT_INT(_POSIX_TZNAME_MAX);
IDENT_INT(_POSIX2_BC_BASE_MAX);
IDENT_INT(_POSIX2_BC_DIM_MAX);
IDENT_INT(_POSIX2_BC_SCALE_MAX);
IDENT_INT(_POSIX2_BC_STRING_MAX);
IDENT_INT(_POSIX2_CHARCLASS_NAME_MAX);
IDENT_INT(_POSIX2_COLL_WEIGHTS_MAX);
IDENT_INT(_POSIX2_EXPR_NEST_MAX);
IDENT_INT(_POSIX2_LINE_MAX);
IDENT_INT(_POSIX2_RE_DUP_MAX);
IDENT_INT(_XOPEN_IOV_MAX);
IDENT_INT(_XOPEN_NAME_MAX);
IDENT_INT(_XOPEN_PATH_MAX);

IDENT_INT(CHAR_BIT);
IDENT_INT(CHAR_MAX);
IDENT_INT(CHAR_MIN);
IDENT_INT(INT_MAX);
IDENT_INT(INT_MIN);
IDENT_INT(LLONG_MAX);
IDENT_INT(LLONG_MIN);
IDENT_INT(LONG_BIT);
IDENT_INT(LONG_MAX);
IDENT_INT(LONG_MIN);
IDENT_INT(MB_LEN_MAX);
IDENT_INT(SCHAR_MAX);
IDENT_INT(SCHAR_MIN);
IDENT_INT(SHRT_MAX);
IDENT_INT(SHRT_MIN);
IDENT_INT(SSIZE_MAX);
IDENT_INT(UCHAR_MAX);
IDENT_INT(UINT_MAX);
IDENT_INT(ULLONG_MAX);
IDENT_INT(ULONG_MAX);
IDENT_INT(USHRT_MAX);
IDENT_INT(WORD_BIT);

IDENT_INT(NL_ARGMAX);
IDENT_INT(NL_LANGMAX);
IDENT_INT(NL_MSGMAX);
IDENT_INT(NL_SETMAX);
IDENT_INT(NL_TEXTMAX);
#ifdef NZERO
IDENT_INT(NZERO);
#endif
