#include <unistd.h>

#include "test_util.h"

IDENT_INT(_POSIX_VERSION);
IDENT_INT(_POSIX2_VERSION);
// TODO(ed): Fix FreeBSD!
// IDENT_INT(_XOPEN_VERSION);

IDENT_INT(_POSIX_ADVISORY_INFO);
IDENT_INT(_POSIX_ASYNCHRONOUS_IO);
IDENT_INT(_POSIX_BARRIERS);
IDENT_INT(_POSIX_CHOWN_RESTRICTED);
IDENT_INT(_POSIX_CLOCK_SELECTION);
IDENT_INT(_POSIX_CPUTIME);
IDENT_INT(_POSIX_FSYNC);
IDENT_INT(_POSIX_IPV6);
IDENT_INT(_POSIX_JOB_CONTROL);
IDENT_INT(_POSIX_MAPPED_FILES);
IDENT_INT(_POSIX_MEMLOCK);
IDENT_INT(_POSIX_MEMLOCK_RANGE);
IDENT_INT(_POSIX_MEMORY_PROTECTION);
IDENT_INT(_POSIX_MESSAGE_PASSING);
IDENT_INT(_POSIX_MONOTONIC_CLOCK);
IDENT_INT(_POSIX_NO_TRUNC);
IDENT_INT(_POSIX_PRIORITIZED_IO);
IDENT_INT(_POSIX_PRIORITY_SCHEDULING);
IDENT_INT(_POSIX_RAW_SOCKETS);
IDENT_INT(_POSIX_READER_WRITER_LOCKS);
IDENT_INT(_POSIX_REALTIME_SIGNALS);
IDENT_INT(_POSIX_REGEXP);
// TODO(ed): Fix FreeBSD!
// IDENT_INT(_POSIX_SAVED_IDS);
IDENT_INT(_POSIX_SEMAPHORES);
IDENT_INT(_POSIX_SHARED_MEMORY_OBJECTS);
IDENT_INT(_POSIX_SHELL);
IDENT_INT(_POSIX_SPAWN);
IDENT_INT(_POSIX_SPIN_LOCKS);
IDENT_INT(_POSIX_SPORADIC_SERVER);
IDENT_INT(_POSIX_SYNCHRONIZED_IO);
IDENT_INT(_POSIX_THREAD_ATTR_STACKADDR);
IDENT_INT(_POSIX_THREAD_ATTR_STACKSIZE);
IDENT_INT(_POSIX_THREAD_CPUTIME);
IDENT_INT(_POSIX_THREAD_PRIO_INHERIT);
IDENT_INT(_POSIX_THREAD_PRIO_PROTECT);
IDENT_INT(_POSIX_THREAD_PRIORITY_SCHEDULING);
IDENT_INT(_POSIX_THREAD_PROCESS_SHARED);
// TODO(ed): Fix FreeBSD!
// IDENT_INT(_POSIX_THREAD_ROBUST_PRIO_INHERIT);
// IDENT_INT(_POSIX_THREAD_ROBUST_PRIO_PROTECT);
IDENT_INT(_POSIX_THREAD_SAFE_FUNCTIONS);
IDENT_INT(_POSIX_THREAD_SPORADIC_SERVER);
IDENT_INT(_POSIX_THREADS);
IDENT_INT(_POSIX_TIMEOUTS);
IDENT_INT(_POSIX_TIMERS);
IDENT_INT(_POSIX_TRACE);
IDENT_INT(_POSIX_TRACE_EVENT_FILTER);
IDENT_INT(_POSIX_TRACE_INHERIT);
IDENT_INT(_POSIX_TRACE_LOG);
IDENT_INT(_POSIX_TYPED_MEMORY_OBJECTS);
// TODO(ed): Fix FreeBSD!
// IDENT_INT(_POSIX_V6_ILP32_OFF32);
// IDENT_INT(_POSIX_V6_ILP32_OFFBIG);
// IDENT_INT(_POSIX_V6_LP64_OFF64);
// IDENT_INT(_POSIX_V6_LPBIG_OFFBIG);
// IDENT_INT(_POSIX_V7_ILP32_OFF32);
// IDENT_INT(_POSIX_V7_ILP32_OFFBIG);
// IDENT_INT(_POSIX_V7_LP64_OFF64);
// IDENT_INT(_POSIX_V7_LPBIG_OFFBIG);
IDENT_INT(_POSIX2_C_BIND);
IDENT_INT(_POSIX2_C_DEV);
IDENT_INT(_POSIX2_CHAR_TERM);
IDENT_INT(_POSIX2_FORT_DEV);
IDENT_INT(_POSIX2_FORT_RUN);
IDENT_INT(_POSIX2_LOCALEDEF);
IDENT_INT(_POSIX2_PBS);
IDENT_INT(_POSIX2_PBS_ACCOUNTING);
IDENT_INT(_POSIX2_PBS_CHECKPOINT);
IDENT_INT(_POSIX2_PBS_LOCATE);
IDENT_INT(_POSIX2_PBS_MESSAGE);
IDENT_INT(_POSIX2_PBS_TRACK);
IDENT_INT(_POSIX2_SW_DEV);
IDENT_INT(_POSIX2_UPE);
IDENT_INT(_XOPEN_CRYPT);
IDENT_INT(_XOPEN_ENH_I18N);
IDENT_INT(_XOPEN_REALTIME);
IDENT_INT(_XOPEN_REALTIME_THREADS);
IDENT_INT(_XOPEN_SHM);
IDENT_INT(_XOPEN_STREAMS);
IDENT_INT(_XOPEN_UNIX);
// TODO(ed): Fix FreeBSD!
// IDENT_INT(_XOPEN_UUCP);

#ifdef _POSIX_ASYNC_IO
IDENT_INT(_POSIX_ASYNC_IO);
#endif
#ifdef _POSIX_PRIO_IO
IDENT_INT(_POSIX_PRIO_IO);
#endif
#ifdef _POSIX_SYNC_IO
IDENT_INT(_POSIX_SYNC_IO);
#endif

#ifdef _POSIX_TIMESTAMP_RESOLUTION
IDENT_INT(_POSIX_TIMESTAMP_RESOLUTION);
#endif
#ifdef _POSIX2_SYMLINKS
IDENT_INT(_POSIX2_SYMLINKS);
#endif

IDENT(NULL, void *);

IDENT_INT(F_OK);
IDENT_INT(R_OK);
IDENT_INT(W_OK);
IDENT_INT(X_OK);

IDENT_INT(_CS_PATH);
// TODO(ed): Fix FreeBSD!
// IDENT_INT(_CS_POSIX_V7_ILP32_OFF32_CFLAGS);
// IDENT_INT(_CS_POSIX_V7_ILP32_OFF32_LDFLAGS);
// IDENT_INT(_CS_POSIX_V7_ILP32_OFF32_LIBS);
// IDENT_INT(_CS_POSIX_V7_ILP32_OFFBIG_CFLAGS);
// IDENT_INT(_CS_POSIX_V7_ILP32_OFFBIG_LDFLAGS);
// IDENT_INT(_CS_POSIX_V7_ILP32_OFFBIG_LIBS);
// IDENT_INT(_CS_POSIX_V7_LP64_OFF64_CFLAGS);
// IDENT_INT(_CS_POSIX_V7_LP64_OFF64_LDFLAGS);
// IDENT_INT(_CS_POSIX_V7_LP64_OFF64_LIBS);
// IDENT_INT(_CS_POSIX_V7_LPBIG_OFFBIG_CFLAGS);
// IDENT_INT(_CS_POSIX_V7_LPBIG_OFFBIG_LDFLAGS);
// IDENT_INT(_CS_POSIX_V7_LPBIG_OFFBIG_LIBS);
// IDENT_INT(_CS_POSIX_V7_THREADS_CFLAGS);
// IDENT_INT(_CS_POSIX_V7_THREADS_LDFLAGS);
// IDENT_INT(_CS_POSIX_V7_WIDTH_RESTRICTED_ENVS);
// IDENT_INT(_CS_V7_ENV);

IDENT_INT(SEEK_CUR);
IDENT_INT(SEEK_END);
IDENT_INT(SEEK_SET);

IDENT_INT(F_LOCK);
IDENT_INT(F_TEST);
IDENT_INT(F_TLOCK);
IDENT_INT(F_ULOCK);

// TODO(ed): Fix FreeBSD!
// IDENT_INT(_PC_2_SYMLINKS);
IDENT_INT(_PC_ALLOC_SIZE_MIN);
IDENT_INT(_PC_ASYNC_IO);
IDENT_INT(_PC_CHOWN_RESTRICTED);
IDENT_INT(_PC_FILESIZEBITS);
IDENT_INT(_PC_LINK_MAX);
IDENT_INT(_PC_MAX_CANON);
IDENT_INT(_PC_MAX_INPUT);
IDENT_INT(_PC_NAME_MAX);
IDENT_INT(_PC_NO_TRUNC);
IDENT_INT(_PC_PATH_MAX);
IDENT_INT(_PC_PIPE_BUF);
IDENT_INT(_PC_PRIO_IO);
IDENT_INT(_PC_REC_INCR_XFER_SIZE);
IDENT_INT(_PC_REC_MAX_XFER_SIZE);
IDENT_INT(_PC_REC_MIN_XFER_SIZE);
IDENT_INT(_PC_REC_XFER_ALIGN);
IDENT_INT(_PC_SYMLINK_MAX);
IDENT_INT(_PC_SYNC_IO);
// TODO(ed): Fix FreeBSD!
// IDENT_INT(_PC_TIMESTAMP_RESOLUTION);
IDENT_INT(_PC_VDISABLE);

IDENT_INT(_SC_2_C_BIND);
IDENT_INT(_SC_2_C_DEV);
IDENT_INT(_SC_2_CHAR_TERM);
IDENT_INT(_SC_2_FORT_DEV);
IDENT_INT(_SC_2_FORT_RUN);
IDENT_INT(_SC_2_LOCALEDEF);
IDENT_INT(_SC_2_PBS);
IDENT_INT(_SC_2_PBS_ACCOUNTING);
IDENT_INT(_SC_2_PBS_CHECKPOINT);
IDENT_INT(_SC_2_PBS_LOCATE);
IDENT_INT(_SC_2_PBS_MESSAGE);
IDENT_INT(_SC_2_PBS_TRACK);
IDENT_INT(_SC_2_SW_DEV);
IDENT_INT(_SC_2_UPE);
IDENT_INT(_SC_2_VERSION);
IDENT_INT(_SC_ADVISORY_INFO);
IDENT_INT(_SC_AIO_LISTIO_MAX);
IDENT_INT(_SC_AIO_MAX);
IDENT_INT(_SC_AIO_PRIO_DELTA_MAX);
IDENT_INT(_SC_ARG_MAX);
IDENT_INT(_SC_ASYNCHRONOUS_IO);
IDENT_INT(_SC_ATEXIT_MAX);
IDENT_INT(_SC_BARRIERS);
IDENT_INT(_SC_BC_BASE_MAX);
IDENT_INT(_SC_BC_DIM_MAX);
IDENT_INT(_SC_BC_SCALE_MAX);
IDENT_INT(_SC_BC_STRING_MAX);
IDENT_INT(_SC_CHILD_MAX);
IDENT_INT(_SC_CLK_TCK);
IDENT_INT(_SC_CLOCK_SELECTION);
IDENT_INT(_SC_COLL_WEIGHTS_MAX);
IDENT_INT(_SC_CPUTIME);
IDENT_INT(_SC_DELAYTIMER_MAX);
IDENT_INT(_SC_EXPR_NEST_MAX);
IDENT_INT(_SC_FSYNC);
IDENT_INT(_SC_GETGR_R_SIZE_MAX);
IDENT_INT(_SC_GETPW_R_SIZE_MAX);
IDENT_INT(_SC_HOST_NAME_MAX);
IDENT_INT(_SC_IOV_MAX);
IDENT_INT(_SC_IPV6);
IDENT_INT(_SC_JOB_CONTROL);
IDENT_INT(_SC_LINE_MAX);
IDENT_INT(_SC_LOGIN_NAME_MAX);
IDENT_INT(_SC_MAPPED_FILES);
IDENT_INT(_SC_MEMLOCK);
IDENT_INT(_SC_MEMLOCK_RANGE);
IDENT_INT(_SC_MEMORY_PROTECTION);
IDENT_INT(_SC_MESSAGE_PASSING);
IDENT_INT(_SC_MONOTONIC_CLOCK);
IDENT_INT(_SC_MQ_OPEN_MAX);
IDENT_INT(_SC_MQ_PRIO_MAX);
IDENT_INT(_SC_NGROUPS_MAX);
IDENT_INT(_SC_OPEN_MAX);
IDENT_INT(_SC_PAGE_SIZE);
IDENT_INT(_SC_PAGESIZE);
IDENT_INT(_SC_PRIORITIZED_IO);
IDENT_INT(_SC_PRIORITY_SCHEDULING);
IDENT_INT(_SC_RAW_SOCKETS);
IDENT_INT(_SC_RE_DUP_MAX);
IDENT_INT(_SC_READER_WRITER_LOCKS);
IDENT_INT(_SC_REALTIME_SIGNALS);
IDENT_INT(_SC_REGEXP);
IDENT_INT(_SC_RTSIG_MAX);
IDENT_INT(_SC_SAVED_IDS);
IDENT_INT(_SC_SEM_NSEMS_MAX);
IDENT_INT(_SC_SEM_VALUE_MAX);
IDENT_INT(_SC_SEMAPHORES);
IDENT_INT(_SC_SHARED_MEMORY_OBJECTS);
IDENT_INT(_SC_SHELL);
IDENT_INT(_SC_SIGQUEUE_MAX);
IDENT_INT(_SC_SPAWN);
IDENT_INT(_SC_SPIN_LOCKS);
IDENT_INT(_SC_SPORADIC_SERVER);
// TODO(ed): Fix FreeBSD!
// IDENT_INT(_SC_SS_REPL_MAX);
IDENT_INT(_SC_STREAM_MAX);
IDENT_INT(_SC_SYMLOOP_MAX);
IDENT_INT(_SC_SYNCHRONIZED_IO);
IDENT_INT(_SC_THREAD_ATTR_STACKADDR);
IDENT_INT(_SC_THREAD_ATTR_STACKSIZE);
IDENT_INT(_SC_THREAD_CPUTIME);
IDENT_INT(_SC_THREAD_DESTRUCTOR_ITERATIONS);
IDENT_INT(_SC_THREAD_KEYS_MAX);
IDENT_INT(_SC_THREAD_PRIO_INHERIT);
IDENT_INT(_SC_THREAD_PRIO_PROTECT);
IDENT_INT(_SC_THREAD_PRIORITY_SCHEDULING);
IDENT_INT(_SC_THREAD_PROCESS_SHARED);
// TODO(ed): Fix FreeBSD!
// IDENT_INT(_SC_THREAD_ROBUST_PRIO_INHERIT);
// IDENT_INT(_SC_THREAD_ROBUST_PRIO_PROTECT);
IDENT_INT(_SC_THREAD_SAFE_FUNCTIONS);
IDENT_INT(_SC_THREAD_SPORADIC_SERVER);
IDENT_INT(_SC_THREAD_STACK_MIN);
IDENT_INT(_SC_THREAD_THREADS_MAX);
IDENT_INT(_SC_THREADS);
IDENT_INT(_SC_TIMEOUTS);
IDENT_INT(_SC_TIMER_MAX);
IDENT_INT(_SC_TIMERS);
IDENT_INT(_SC_TRACE);
IDENT_INT(_SC_TRACE_EVENT_FILTER);
// TODO(ed): Fix FreeBSD!
// IDENT_INT(_SC_TRACE_EVENT_NAME_MAX);
IDENT_INT(_SC_TRACE_INHERIT);
IDENT_INT(_SC_TRACE_LOG);
// TODO(ed): Fix FreeBSD!
// IDENT_INT(_SC_TRACE_NAME_MAX);
// IDENT_INT(_SC_TRACE_SYS_MAX);
// IDENT_INT(_SC_TRACE_USER_EVENT_MAX);
IDENT_INT(_SC_TTY_NAME_MAX);
IDENT_INT(_SC_TYPED_MEMORY_OBJECTS);
IDENT_INT(_SC_TZNAME_MAX);
// TODO(ed): Fix FreeBSD!
// IDENT_INT(_SC_V7_ILP32_OFF32);
// IDENT_INT(_SC_V7_ILP32_OFFBIG);
// IDENT_INT(_SC_V7_LP64_OFF64);
// IDENT_INT(_SC_V7_LPBIG_OFFBIG);
IDENT_INT(_SC_V6_ILP32_OFF32);
IDENT_INT(_SC_V6_ILP32_OFFBIG);
IDENT_INT(_SC_V6_LP64_OFF64);
IDENT_INT(_SC_V6_LPBIG_OFFBIG);
IDENT_INT(_SC_VERSION);
IDENT_INT(_SC_XOPEN_CRYPT);
IDENT_INT(_SC_XOPEN_ENH_I18N);
IDENT_INT(_SC_XOPEN_REALTIME);
IDENT_INT(_SC_XOPEN_REALTIME_THREADS);
IDENT_INT(_SC_XOPEN_SHM);
IDENT_INT(_SC_XOPEN_STREAMS);
IDENT_INT(_SC_XOPEN_UNIX);
// TODO(ed): Fix FreeBSD!
// IDENT_INT(_SC_XOPEN_UUCP);
IDENT_INT(_SC_XOPEN_VERSION);

IDENT(STDERR_FILENO, int);
IDENT(STDIN_FILENO, int);
IDENT(STDOUT_FILENO, int);

IDENT_INT(_POSIX_VDISABLE);

TYPE_UINT(size_t);
TYPE_SINT(ssize_t);
TYPE_INT(uid_t);
TYPE_INT(gid_t);
TYPE_SINT(off_t);
TYPE_SINT(pid_t);

TYPE_SINT(intptr_t);

IDENT(access, int (*)(const char *, int));
IDENT(alarm, unsigned (*)(unsigned));
IDENT(chdir, int (*)(const char *));
IDENT(chown, int (*)(const char *, uid_t, gid_t));
IDENT(close, int (*)(int));
IDENT(confstr, size_t (*)(int, char *, size_t));
IDENT(crypt, char *(*)(const char *, const char *));
IDENT(dup, int (*)(int));
IDENT(dup2, int (*)(int, int));
IDENT(_exit, void (*)(int));
// TODO(ed): Fix FreeBSD!
// IDENT(encrypt, void (*)(char[64], int));
IDENT(execl, int (*)(const char *, const char *, ...));
IDENT(execle, int (*)(const char *, const char *, ...));
IDENT(execlp, int (*)(const char *, const char *, ...));
IDENT(execv, int (*)(const char *, char *const[]));
IDENT(execve, int (*)(const char *, char *const[], char *const[]));
IDENT(execvp, int (*)(const char *, char *const[]));
IDENT(faccessat, int (*)(int, const char *, int, int));
IDENT(fchdir, int (*)(int));
IDENT(fchown, int (*)(int, uid_t, gid_t));
IDENT(fchownat, int (*)(int, const char *, uid_t, gid_t, int));
// TODO(ed): Fix FreeBSD!
// IDENT(fdatasync, int (*)(int));
IDENT(fexecve, int (*)(int, char *const[], char *const[]));
IDENT(fork, pid_t (*)(void));
IDENT(fpathconf, long (*)(int, int));
IDENT(fsync, int (*)(int));
IDENT(ftruncate, int (*)(int, off_t));
IDENT(getcwd, char *(*)(char *, size_t));
IDENT(getegid, gid_t (*)(void));
IDENT(geteuid, uid_t (*)(void));
IDENT(getgid, gid_t (*)(void));
IDENT(getgroups, int (*)(int, gid_t[]));
IDENT(gethostid, long (*)(void));
IDENT(gethostname, int (*)(char *, size_t));
IDENT(getlogin, char *(*)(void));
// TODO(ed): Fix FreeBSD!
// IDENT(getlogin_r, int (*)(char *, size_t));
IDENT(getopt, int (*)(int, char *const[], const char *));
IDENT(getpgid, pid_t (*)(pid_t));
IDENT(getpgrp, pid_t (*)(void));
IDENT(getpid, pid_t (*)(void));
IDENT(getppid, pid_t (*)(void));
IDENT(getsid, pid_t (*)(pid_t));
IDENT(getuid, uid_t (*)(void));
IDENT(isatty, int (*)(int));
IDENT(lchown, int (*)(const char *, uid_t, gid_t));
IDENT(link, int (*)(const char *, const char *));
IDENT(linkat, int (*)(int, const char *, int, const char *, int));
IDENT(lockf, int (*)(int, int, off_t));
IDENT(lseek, off_t (*)(int, off_t, int));
IDENT(nice, int (*)(int));
IDENT(pathconf, long (*)(const char *, int));
IDENT(pause, int (*)(void));
IDENT(pipe, int (*)(int[2]));
IDENT(pread, ssize_t (*)(int, void *, size_t, off_t));
IDENT(pwrite, ssize_t (*)(int, const void *, size_t, off_t));
IDENT(read, ssize_t (*)(int, void *, size_t));
IDENT(readlink, ssize_t (*)(const char *restrict, char *restrict, size_t));
IDENT(readlinkat,
      ssize_t (*)(int, const char *restrict, char *restrict, size_t));
IDENT(rmdir, int (*)(const char *));
IDENT(setegid, int (*)(gid_t));
IDENT(seteuid, int (*)(uid_t));
IDENT(setgid, int (*)(gid_t));
IDENT(setpgid, int (*)(pid_t, pid_t));
IDENT(setregid, int (*)(gid_t, gid_t));
IDENT(setreuid, int (*)(uid_t, uid_t));
IDENT(setsid, pid_t (*)(void));
IDENT(setuid, int (*)(uid_t));
IDENT(sleep, unsigned (*)(unsigned));
IDENT(swab, void (*)(const void *restrict, void *restrict, ssize_t));
IDENT(symlink, int (*)(const char *, const char *));
IDENT(symlinkat, int (*)(const char *, int, const char *));
IDENT(sync, void (*)(void));
IDENT(sysconf, long (*)(int));
IDENT(tcgetpgrp, pid_t (*)(int));
IDENT(tcsetpgrp, int (*)(int, pid_t));
IDENT(truncate, int (*)(const char *, off_t));
IDENT(ttyname, char *(*)(int));
IDENT(ttyname_r, int (*)(int, char *, size_t));
IDENT(unlink, int (*)(const char *));
IDENT(unlinkat, int (*)(int, const char *, int));
IDENT(write, ssize_t (*)(int, const void *, size_t));

IDENT(optarg, char *);
IDENT(opterr, int);
IDENT(optind, int);
IDENT(optopt, int);
