#include <termios.h>

#include "test_util.h"

TYPE_INT(cc_t);
TYPE_INT(speed_t);
TYPE_INT(tcflag_t);

TYPE(struct termios);
MEMBER(struct termios, c_iflag, tcflag_t);
MEMBER(struct termios, c_oflag, tcflag_t);
MEMBER(struct termios, c_cflag, tcflag_t);
MEMBER(struct termios, c_lflag, tcflag_t);
MEMBER(struct termios, c_cc, cc_t *);

IDENT_INT(NCCS);

IDENT_INT(VEOF);
IDENT_INT(VEOL);
IDENT_INT(VERASE);
IDENT_INT(VINTR);
IDENT_INT(VKILL);
IDENT_INT(VMIN);
IDENT_INT(VQUIT);
IDENT_INT(VSTART);
IDENT_INT(VSTOP);
IDENT_INT(VSUSP);
IDENT_INT(VTIME);

IDENT_INT(BRKINT);
IDENT_INT(ICRNL);
IDENT_INT(IGNBRK);
IDENT_INT(IGNCR);
IDENT_INT(IGNPAR);
IDENT_INT(INLCR);
IDENT_INT(INPCK);
IDENT_INT(ISTRIP);
IDENT_INT(IXANY);
IDENT_INT(IXOFF);
IDENT_INT(IXON);
IDENT_INT(PARMRK);

IDENT_INT(OPOST);
IDENT_INT(ONLCR);
IDENT_INT(OCRNL);
IDENT_INT(ONOCR);
IDENT_INT(ONLRET);
#ifdef OFDEL
IDENT_INT(OFDEL);
#endif
#ifdef OFILL
IDENT_INT(OFILL);
#endif
#ifdef NLDLY
IDENT_INT(NLDLY);
IDENT_INT(NL0);
IDENT_INT(NL1);
#endif
#ifdef CRDLY
IDENT_INT(CRDLY);
IDENT_INT(CR0);
IDENT_INT(CR1);
IDENT_INT(CR2);
IDENT_INT(CR3);
#endif
#ifdef TABDLY
IDENT_INT(TABDLY);
IDENT_INT(TAB0);
#ifdef TAB1
IDENT_INT(TAB1);
#endif
#ifdef TAB2
IDENT_INT(TAB2);
#endif
IDENT_INT(TAB3);
#endif
#ifdef BSDLY
IDENT_INT(BSDLY);
IDENT_INT(BS0);
IDENT_INT(BS1);
#endif
#ifdef VTDLY
IDENT_INT(VTDLY);
IDENT_INT(VT0);
IDENT_INT(VT1);
#endif
#ifdef FFDLY
IDENT_INT(FFDLY);
IDENT_INT(FF0);
IDENT_INT(FF1);
#endif

IDENT_INT(B0);
IDENT_INT(B50);
IDENT_INT(B75);
IDENT_INT(B110);
IDENT_INT(B134);
IDENT_INT(B150);
IDENT_INT(B200);
IDENT_INT(B300);
IDENT_INT(B600);
IDENT_INT(B1200);
IDENT_INT(B1800);
IDENT_INT(B2400);
IDENT_INT(B4800);
IDENT_INT(B9600);
IDENT_INT(B19200);
IDENT_INT(B38400);

IDENT_INT(CSIZE);
IDENT_INT(CS5);
IDENT_INT(CS6);
IDENT_INT(CS7);
IDENT_INT(CS8);
IDENT_INT(CSTOPB);
IDENT_INT(CREAD);
IDENT_INT(PARENB);
IDENT_INT(PARODD);
IDENT_INT(HUPCL);
IDENT_INT(CLOCAL);

IDENT_INT(ECHO);
IDENT_INT(ECHOE);
IDENT_INT(ECHOK);
IDENT_INT(ECHONL);
IDENT_INT(ICANON);
IDENT_INT(IEXTEN);
IDENT_INT(ISIG);
IDENT_INT(NOFLSH);
IDENT_INT(TOSTOP);

IDENT_INT(TCSANOW);
IDENT_INT(TCSADRAIN);
IDENT_INT(TCSAFLUSH);

IDENT_INT(TCIFLUSH);
IDENT_INT(TCIOFLUSH);
IDENT_INT(TCOFLUSH);

IDENT_INT(TCIOFF);
IDENT_INT(TCION);
IDENT_INT(TCOOFF);
IDENT_INT(TCOON);

IDENT(cfgetispeed, speed_t (*)(const struct termios *));
IDENT(cfgetospeed, speed_t (*)(const struct termios *));
IDENT(cfsetispeed, int (*)(struct termios *, speed_t));
IDENT(cfsetospeed, int (*)(struct termios *, speed_t));
IDENT(tcdrain, int (*)(int));
IDENT(tcflow, int (*)(int, int));
IDENT(tcflush, int (*)(int, int));
IDENT(tcgetattr, int (*)(int, struct termios *));
IDENT(tcgetsid, pid_t (*)(int));
IDENT(tcsendbreak, int (*)(int, int));
IDENT(tcsetattr, int (*)(int, int, const struct termios *));
