#ifndef TRANSITIVE
#include <math.h>
#endif

#include "test_util.h"

TYPE_ARITH(float_t);
TYPE_ARITH(double_t);

IDENT(fpclassify(0.0), int);
IDENT(isfinite(0.0), int);
IDENT(isgreater(0.0, 0.0), int);
IDENT(isgreaterequal(0.0, 0.0), int);
IDENT(isinf(0.0), int);
IDENT(isless(0.0, 0.0), int);
IDENT(islessequal(0.0, 0.0), int);
IDENT(islessgreater(0.0, 0.0), int);
IDENT(isnan(0.0), int);
IDENT(isnormal(0.0), int);
IDENT(isunordered(0.0, 0.0), int);
IDENT(signbit(0.0), int);

IDENT(M_E, double);
IDENT(M_LOG2E, double);
IDENT(M_LOG10E, double);
IDENT(M_LN2, double);
IDENT(M_LN10, double);
IDENT(M_PI, double);
IDENT(M_PI_2, double);
IDENT(M_PI_4, double);
IDENT(M_1_PI, double);
IDENT(M_2_PI, double);
IDENT(M_2_SQRTPI, double);
IDENT(M_SQRT2, double);
IDENT(M_SQRT1_2, double);

#ifdef MAXFLOAT
IDENT(MAXFLOAT, float);
#endif

IDENT(HUGE_VAL, double);
IDENT(HUGE_VALF, float);
IDENT(HUGE_VALL, long double);
IDENT(INFINITY, float);
IDENT(NAN, float);

IDENT_INT(FP_INFINITE);
IDENT_INT(FP_NAN);
IDENT_INT(FP_NORMAL);
IDENT_INT(FP_SUBNORMAL);
IDENT_INT(FP_ZERO);

IDENT_INT(FP_ILOGB0);
IDENT_INT(FP_ILOGBNAN);

IDENT_INT(MATH_ERRNO);
IDENT_INT(MATH_ERREXCEPT);

IDENT(acos, double (*)(double));
IDENT(acosf, float (*)(float));
IDENT(acosh, double (*)(double));
IDENT(acoshf, float (*)(float));
IDENT(acoshl, long double (*)(long double));
IDENT(acosl, long double (*)(long double));
IDENT(asin, double (*)(double));
IDENT(asinf, float (*)(float));
IDENT(asinh, double (*)(double));
IDENT(asinhf, float (*)(float));
IDENT(asinhl, long double (*)(long double));
IDENT(asinl, long double (*)(long double));
IDENT(atan, double (*)(double));
IDENT(atan2, double (*)(double, double));
IDENT(atan2f, float (*)(float, float));
IDENT(atan2l, long double (*)(long double, long double));
IDENT(atanf, float (*)(float));
IDENT(atanh, double (*)(double));
IDENT(atanhf, float (*)(float));
IDENT(atanhl, long double (*)(long double));
IDENT(atanl, long double (*)(long double));
IDENT(cbrt, double (*)(double));
IDENT(cbrtf, float (*)(float));
IDENT(cbrtl, long double (*)(long double));
IDENT(ceil, double (*)(double));
IDENT(ceilf, float (*)(float));
IDENT(ceill, long double (*)(long double));
IDENT(copysign, double (*)(double, double));
IDENT(copysignf, float (*)(float, float));
IDENT(copysignl, long double (*)(long double, long double));
IDENT(cos, double (*)(double));
IDENT(cosf, float (*)(float));
IDENT(cosh, double (*)(double));
IDENT(coshf, float (*)(float));
IDENT(coshl, long double (*)(long double));
IDENT(cosl, long double (*)(long double));
IDENT(erf, double (*)(double));
IDENT(erfc, double (*)(double));
IDENT(erfcf, float (*)(float));
IDENT(erfcl, long double (*)(long double));
IDENT(erff, float (*)(float));
IDENT(erfl, long double (*)(long double));
IDENT(exp, double (*)(double));
IDENT(exp2, double (*)(double));
IDENT(exp2f, float (*)(float));
IDENT(exp2l, long double (*)(long double));
IDENT(expf, float (*)(float));
IDENT(expl, long double (*)(long double));
IDENT(expm1, double (*)(double));
IDENT(expm1f, float (*)(float));
IDENT(expm1l, long double (*)(long double));
IDENT(fabs, double (*)(double));
IDENT(fabsf, float (*)(float));
IDENT(fabsl, long double (*)(long double));
IDENT(fdim, double (*)(double, double));
IDENT(fdimf, float (*)(float, float));
IDENT(fdiml, long double (*)(long double, long double));
IDENT(floor, double (*)(double));
IDENT(floorf, float (*)(float));
IDENT(floorl, long double (*)(long double));
IDENT(fma, double (*)(double, double, double));
IDENT(fmaf, float (*)(float, float, float));
IDENT(fmal, long double (*)(long double, long double, long double));
IDENT(fmax, double (*)(double, double));
IDENT(fmaxf, float (*)(float, float));
IDENT(fmaxl, long double (*)(long double, long double));
IDENT(fmin, double (*)(double, double));
IDENT(fminf, float (*)(float, float));
IDENT(fminl, long double (*)(long double, long double));
IDENT(fmod, double (*)(double, double));
IDENT(fmodf, float (*)(float, float));
IDENT(fmodl, long double (*)(long double, long double));
IDENT(frexp, double (*)(double, int *));
IDENT(frexpf, float (*)(float, int *));
IDENT(frexpl, long double (*)(long double, int *));
IDENT(hypot, double (*)(double, double));
IDENT(hypotf, float (*)(float, float));
IDENT(hypotl, long double (*)(long double, long double));
IDENT(ilogb, int (*)(double));
IDENT(ilogbf, int (*)(float));
IDENT(ilogbl, int (*)(long double));
IDENT(j0, double (*)(double));
IDENT(j1, double (*)(double));
IDENT(jn, double (*)(int, double));
IDENT(ldexp, double (*)(double, int));
IDENT(ldexpf, float (*)(float, int));
IDENT(ldexpl, long double (*)(long double, int));
IDENT(lgamma, double (*)(double));
IDENT(lgammaf, float (*)(float));
IDENT(lgammal, long double (*)(long double));
IDENT(llrint, long long (*)(double));
IDENT(llrintf, long long (*)(float));
IDENT(llrintl, long long (*)(long double));
IDENT(llround, long long (*)(double));
IDENT(llroundf, long long (*)(float));
IDENT(llroundl, long long (*)(long double));
IDENT(log, double (*)(double));
IDENT(log10, double (*)(double));
IDENT(log10f, float (*)(float));
IDENT(log10l, long double (*)(long double));
IDENT(log1p, double (*)(double));
IDENT(log1pf, float (*)(float));
IDENT(log1pl, long double (*)(long double));
IDENT(log2, double (*)(double));
IDENT(log2f, float (*)(float));
IDENT(log2l, long double (*)(long double));
IDENT(logb, double (*)(double));
IDENT(logbf, float (*)(float));
IDENT(logbl, long double (*)(long double));
IDENT(logf, float (*)(float));
IDENT(logl, long double (*)(long double));
IDENT(lrint, long (*)(double));
IDENT(lrintf, long (*)(float));
IDENT(lrintl, long (*)(long double));
IDENT(lround, long (*)(double));
IDENT(lroundf, long (*)(float));
IDENT(lroundl, long (*)(long double));
IDENT(modf, double (*)(double, double *));
IDENT(modff, float (*)(float, float *));
IDENT(modfl, long double (*)(long double, long double *));
IDENT(nan, double (*)(const char *));
IDENT(nanf, float (*)(const char *));
IDENT(nanl, long double (*)(const char *));
IDENT(nearbyint, double (*)(double));
IDENT(nearbyintf, float (*)(float));
IDENT(nearbyintl, long double (*)(long double));
IDENT(nextafter, double (*)(double, double));
IDENT(nextafterf, float (*)(float, float));
IDENT(nextafterl, long double (*)(long double, long double));
IDENT(nexttoward, double (*)(double, long double));
IDENT(nexttowardf, float (*)(float, long double));
IDENT(nexttowardl, long double (*)(long double, long double));
IDENT(pow, double (*)(double, double));
IDENT(powf, float (*)(float, float));
IDENT(powl, long double (*)(long double, long double));
IDENT(remainder, double (*)(double, double));
IDENT(remainderf, float (*)(float, float));
IDENT(remainderl, long double (*)(long double, long double));
IDENT(remquo, double (*)(double, double, int *));
IDENT(remquof, float (*)(float, float, int *));
IDENT(remquol, long double (*)(long double, long double, int *));
IDENT(rint, double (*)(double));
IDENT(rintf, float (*)(float));
IDENT(rintl, long double (*)(long double));
IDENT(round, double (*)(double));
IDENT(roundf, float (*)(float));
IDENT(roundl, long double (*)(long double));
IDENT(scalbln, double (*)(double, long));
IDENT(scalblnf, float (*)(float, long));
IDENT(scalblnl, long double (*)(long double, long));
IDENT(scalbn, double (*)(double, int));
IDENT(scalbnf, float (*)(float, int));
IDENT(scalbnl, long double (*)(long double, int));
IDENT(sin, double (*)(double));
IDENT(sinf, float (*)(float));
IDENT(sinh, double (*)(double));
IDENT(sinhf, float (*)(float));
IDENT(sinhl, long double (*)(long double));
IDENT(sinl, long double (*)(long double));
IDENT(sqrt, double (*)(double));
IDENT(sqrtf, float (*)(float));
IDENT(sqrtl, long double (*)(long double));
IDENT(tan, double (*)(double));
IDENT(tanf, float (*)(float));
IDENT(tanh, double (*)(double));
IDENT(tanhf, float (*)(float));
IDENT(tanhl, long double (*)(long double));
IDENT(tanl, long double (*)(long double));
IDENT(tgamma, double (*)(double));
IDENT(tgammaf, float (*)(float));
IDENT(tgammal, long double (*)(long double));
IDENT(trunc, double (*)(double));
IDENT(truncf, float (*)(float));
IDENT(truncl, long double (*)(long double));
IDENT(y0, double (*)(double));
IDENT(y1, double (*)(double));
IDENT(yn, double (*)(int, double));

IDENT(signgam, int);
