#include <inttypes.h>

#include "test_util.h"

TYPE(imaxdiv_t);
MEMBER(imaxdiv_t, quot, intmax_t);
MEMBER(imaxdiv_t, rem, intmax_t);
TYPE_INT(wchar_t);

IDENT(PRId8, char *);
IDENT(PRId16, char *);
IDENT(PRId32, char *);
IDENT(PRId64, char *);
IDENT(PRIdLEAST8, char *);
IDENT(PRIdLEAST16, char *);
IDENT(PRIdLEAST32, char *);
IDENT(PRIdLEAST64, char *);
IDENT(PRIdFAST8, char *);
IDENT(PRIdFAST16, char *);
IDENT(PRIdFAST32, char *);
IDENT(PRIdFAST64, char *);
IDENT(PRIdMAX, char *);
IDENT(PRIdPTR, char *);
IDENT(PRIi8, char *);
IDENT(PRIi16, char *);
IDENT(PRIi32, char *);
IDENT(PRIi64, char *);
IDENT(PRIiLEAST8, char *);
IDENT(PRIiLEAST16, char *);
IDENT(PRIiLEAST32, char *);
IDENT(PRIiLEAST64, char *);
IDENT(PRIiFAST8, char *);
IDENT(PRIiFAST16, char *);
IDENT(PRIiFAST32, char *);
IDENT(PRIiFAST64, char *);
IDENT(PRIiMAX, char *);
IDENT(PRIiPTR, char *);

IDENT(PRIo8, char *);
IDENT(PRIo16, char *);
IDENT(PRIo32, char *);
IDENT(PRIo64, char *);
IDENT(PRIoLEAST8, char *);
IDENT(PRIoLEAST16, char *);
IDENT(PRIoLEAST32, char *);
IDENT(PRIoLEAST64, char *);
IDENT(PRIoFAST8, char *);
IDENT(PRIoFAST16, char *);
IDENT(PRIoFAST32, char *);
IDENT(PRIoFAST64, char *);
IDENT(PRIoMAX, char *);
IDENT(PRIoPTR, char *);
IDENT(PRIu8, char *);
IDENT(PRIu16, char *);
IDENT(PRIu32, char *);
IDENT(PRIu64, char *);
IDENT(PRIuLEAST8, char *);
IDENT(PRIuLEAST16, char *);
IDENT(PRIuLEAST32, char *);
IDENT(PRIuLEAST64, char *);
IDENT(PRIuFAST8, char *);
IDENT(PRIuFAST16, char *);
IDENT(PRIuFAST32, char *);
IDENT(PRIuFAST64, char *);
IDENT(PRIuMAX, char *);
IDENT(PRIuPTR, char *);
IDENT(PRIx8, char *);
IDENT(PRIx16, char *);
IDENT(PRIx32, char *);
IDENT(PRIx64, char *);
IDENT(PRIxLEAST8, char *);
IDENT(PRIxLEAST16, char *);
IDENT(PRIxLEAST32, char *);
IDENT(PRIxLEAST64, char *);
IDENT(PRIxFAST8, char *);
IDENT(PRIxFAST16, char *);
IDENT(PRIxFAST32, char *);
IDENT(PRIxFAST64, char *);
IDENT(PRIxMAX, char *);
IDENT(PRIxPTR, char *);
IDENT(PRIX8, char *);
IDENT(PRIX16, char *);
IDENT(PRIX32, char *);
IDENT(PRIX64, char *);
IDENT(PRIXLEAST8, char *);
IDENT(PRIXLEAST16, char *);
IDENT(PRIXLEAST32, char *);
IDENT(PRIXLEAST64, char *);
IDENT(PRIXFAST8, char *);
IDENT(PRIXFAST16, char *);
IDENT(PRIXFAST32, char *);
IDENT(PRIXFAST64, char *);
IDENT(PRIXMAX, char *);
IDENT(PRIXPTR, char *);

IDENT(SCNd8, char *);
IDENT(SCNd16, char *);
IDENT(SCNd32, char *);
IDENT(SCNd64, char *);
IDENT(SCNdLEAST8, char *);
IDENT(SCNdLEAST16, char *);
IDENT(SCNdLEAST32, char *);
IDENT(SCNdLEAST64, char *);
IDENT(SCNdFAST8, char *);
IDENT(SCNdFAST16, char *);
IDENT(SCNdFAST32, char *);
IDENT(SCNdFAST64, char *);
IDENT(SCNdMAX, char *);
IDENT(SCNdPTR, char *);
IDENT(SCNi8, char *);
IDENT(SCNi16, char *);
IDENT(SCNi32, char *);
IDENT(SCNi64, char *);
IDENT(SCNiLEAST8, char *);
IDENT(SCNiLEAST16, char *);
IDENT(SCNiLEAST32, char *);
IDENT(SCNiLEAST64, char *);
IDENT(SCNiFAST8, char *);
IDENT(SCNiFAST16, char *);
IDENT(SCNiFAST32, char *);
IDENT(SCNiFAST64, char *);
IDENT(SCNiMAX, char *);
IDENT(SCNiPTR, char *);

IDENT(SCNo8, char *);
IDENT(SCNo16, char *);
IDENT(SCNo32, char *);
IDENT(SCNo64, char *);
IDENT(SCNoLEAST8, char *);
IDENT(SCNoLEAST16, char *);
IDENT(SCNoLEAST32, char *);
IDENT(SCNoLEAST64, char *);
IDENT(SCNoFAST8, char *);
IDENT(SCNoFAST16, char *);
IDENT(SCNoFAST32, char *);
IDENT(SCNoFAST64, char *);
IDENT(SCNoMAX, char *);
IDENT(SCNoPTR, char *);
IDENT(SCNu8, char *);
IDENT(SCNu16, char *);
IDENT(SCNu32, char *);
IDENT(SCNu64, char *);
IDENT(SCNuLEAST8, char *);
IDENT(SCNuLEAST16, char *);
IDENT(SCNuLEAST32, char *);
IDENT(SCNuLEAST64, char *);
IDENT(SCNuFAST8, char *);
IDENT(SCNuFAST16, char *);
IDENT(SCNuFAST32, char *);
IDENT(SCNuFAST64, char *);
IDENT(SCNuMAX, char *);
IDENT(SCNuPTR, char *);
IDENT(SCNx8, char *);
IDENT(SCNx16, char *);
IDENT(SCNx32, char *);
IDENT(SCNx64, char *);
IDENT(SCNxLEAST8, char *);
IDENT(SCNxLEAST16, char *);
IDENT(SCNxLEAST32, char *);
IDENT(SCNxLEAST64, char *);
IDENT(SCNxFAST8, char *);
IDENT(SCNxFAST16, char *);
IDENT(SCNxFAST32, char *);
IDENT(SCNxFAST64, char *);
IDENT(SCNxMAX, char *);
IDENT(SCNxPTR, char *);

IDENT(imaxabs, intmax_t (*)(intmax_t));
IDENT(imaxdiv, imaxdiv_t (*)(intmax_t, intmax_t));
IDENT(strtoimax, intmax_t (*)(const char *restrict, char **restrict, int));
IDENT(strtoumax, uintmax_t (*)(const char *restrict, char **restrict, int));
IDENT(wcstoimax,
      intmax_t (*)(const wchar_t *restrict, wchar_t **restrict, int));
IDENT(wcstoumax,
      uintmax_t (*)(const wchar_t *restrict, wchar_t **restrict, int));

#define TRANSITIVE
#include "test_stdint.c"
